apiVersion: v1
kind: Service
metadata:
  name: chat-gpt-svc
  labels:
    app: chat-gpt
  annotations:
    {{ if eq .Values.deliveryMode "public" }}
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-charge-type: "paybybandwidth"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-bandwidth: "10"
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: "slb.s2.small"
    {{ end }}
    networking.alibaba.com/ip-family: SingleStack
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  {{ if eq .Values.deliveryMode "public" }}
  type: LoadBalancer
  {{ else }}
  type: ClusterIP
  {{ end }}
  ports:
    - port: 80
      name: http-server
      targetPort: http-server
  selector:
    app: chat-gpt